Para ir guardando datos:

In [1]:
v = zeros(10) # crear con tamaño conocido de antemano

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [2]:
v[3]

0.0

In [3]:
v[3] = 10

10

In [4]:
v

10-element Array{Float64,1}:
  0.0
  0.0
 10.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0

## Crear un arreglo vacío:

In [5]:
v = [0.3]

1-element Array{Float64,1}:
 0.3

In [6]:
push!(v, 10)

2-element Array{Float64,1}:
  0.3
 10.0

In [7]:
push!(v, 100)

3-element Array{Float64,1}:
   0.3
  10.0
 100.0